export const ENDPOINTS = {
  auth: {
    base: '/api',
    login: '/api/login',
    register: '/api/register',
    changePassword: '/api/reset-password',
    google: '/api/login-google',
    requestResetPassword: '/api/forget-password',
    upRoleTutor: '/api/up-role',
  },
  users: {
    update: '/api/account',
    userId: id => `/api/account/${id}`,
  },
  subjects: {
    base: '/api/subject',
    subjectId: id => `/api/subject/${id}`,
    subjectName: name => `/api/subject/${name}`,
    location: '/api/location',
    grade: '/api/grade',
    educationLevel: '/api/education-level',
    weekDay: '/api/week-days',
    teachingSlot: '/api/teaching-slots',
    register: '/api/subject/register-for-tutor',
    tutor: '/api/approved-registration',
  },
  booking: {
    base: '/api/bookings/booking',
    detail: id => `/api/bookings/booking/${id}`,
    idTutor: id => `/api/bookings/tutor-bookings/${id}`,
    idStudent: id => `/api/bookings/student-bookings/${id}`,
    approve: '/api/bookings/approved-booking',
    reject: '/api/bookings/rejected-booking',
    pass: '/api/bookings/passed-course',
  },
  payment: {
    base: '/api/request-recharge-vnpay',
    wallet: id => `/api/walletDetail/${id}`,
    update: '/api/update-money',
    package: '/api/monthly-package',
  },
  reviews: {
    base: '/api/review',
    review: tutorId => `/api/reviews/tutor/${tutorId}`,
  },
  complaints: {
    base: '/api/complaints',
    complaint: '/api/complaint',
    pending: '/api/pending-complaint',
    approve: id => `/api/complaint/approved/${id}`,
    reject: id => `/api/complaint/rejected/${id}`,
  },
};
